//Prime numebers can also be generated by using Sieve of Eratosthenes algorithm
//This algorithm is used to generate all prime numbers less than or equal to a given integer n
/*
write a program that implements this algorithm, have the program fins all the prime numbers up to n = 150
To display all the prime numbers between 1 and n
step1: create an array of n elements and initialize all elements to 0,
2<=i < n
step2:  set i to 2
step3: if i > n, the algorithm terminates
step4: if p[i] = 0, then i is a prime number, display i
step5: for all positive integers j, j*i <= n, set p[j*i] = 1
step6: increment i by 1 and go to step 3
*/
#include <stdio.h>

int main() {
    const int n = 150;
    int primes[n+1]; // Array to store prime numbers, initialized to 0
    int i, j;

    // Step 1: Initialize all elements of the primes array to 0
    for (i = 0; i <= n; ++i) {
        primes[i] = 0;
    }

    // Step 2: Start with i = 2
    i = 2;

    // Step 3: Loop until i > n
    while (i <= n) {
        // Step 4: If p[i] == 0, then i is a prime number, display i
        if (primes[i] == 0) {
            printf("%d ", i);
        }
        // Step 5: Set primes[j*i] = 1 for all positive integers j such that j*i <= n
        for (j = 2; j * i <= n; ++j) {
            primes[j * i] = 1;
        }
        // Step 6: Increment i by 1
        ++i;
    }

    printf("\n");

    return 0;
}
